# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yang Liu
description: >- # this means to ignore newlines until "baseurl:"
  Yang is a first-year PhD student.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io"# the base hostname & protocol for the site "https://eliottvincent.github.io"
og_image: /assets/img/self_profile_after.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Publications
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yang.9.liu@kcl.ac.uk
      link: mailto:yourmail@domain.com
    #- name: WeChat
    #  value: YourWeChatUsername
    #  link: "#"
  follow:
    #- name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
    - name: Facebook
      #link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      #link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      #link: http://github.com/YourGitHubUsername
    - name: GoogleScholar
      link: https://scholar.google.com/citations?view_op=list_works&hl=en&authuser=1&hl=en&user=Fgh4hTUAAAAJ&authuser=1

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
